In [15]:
#python basics

In [16]:
print("hello world")

hello world


In [17]:
print(5*6)

30


In [18]:
l=[1,2,3,4]
1

1

In [19]:
s=["windows", "linux", "mac"]
s

['windows', 'linux', 'mac']

In [20]:
x=[1, "hi", 4.03]
x

[1, 'hi', 4.03]

In [21]:
t=("hi", "hello", "how are you")
t

('hi', 'hello', 'how are you')

In [22]:
t=("hi", 4.0)
t

('hi', 4.0)

In [23]:
a=4
if a%2==0:
    print(1)
else:
    print(0)

1


In [24]:
i=1
while i<5:
    print(i)
    i=i+1

1
2
3
4


In [25]:
vegetables=["potato", "cabbage", "onion"]
for x in vegetables:
    print(x)

potato
cabbage
onion


In [26]:
def myfunction(a):
    if a%2==0:
        return 1
    else:
        return 0
myfunction(5)

0

In [27]:
x=lambda a:a+1
print(x(5))

6


In [28]:
#numpy basics

In [29]:
import numpy as np

In [30]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [31]:
a[-1]

4

In [32]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
c=b.copy()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
d=b.view()
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
b[6]=12
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
d

array([ 1,  2,  3,  4,  5,  6, 12,  8,  9])

In [37]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [38]:
c=np.array([13,14,15])
d=np.concatenate((a,c))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
np.array_split(d,2)

[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15])]

In [40]:
np.where(d==4)

(array([3], dtype=int64),)

In [41]:
np.where(d%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13], dtype=int64),)

In [42]:
c=np.array([3,4,2,10,5])
np.sort(c)

array([ 2,  3,  4,  5, 10])

In [43]:
c=np.array([[2,3,1,5],[5,1,2,4]])
np.sort(c)

array([[1, 2, 3, 5],
       [1, 2, 4, 5]])

In [44]:
c=np.array(["apple", "orange", "banana", "mango"])
np.sort(c)

array(['apple', 'banana', 'mango', 'orange'], dtype='<U6')

In [45]:
np.random.randint(100)

56

In [46]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [47]:
np.ones(2)

array([1., 1.])

In [48]:
##pandas basics

In [49]:
import numpy as np
import pandas as pd


dict1={
    "Name":["Rohan", "seema", "Mahesh", "Shruthi"],
    "Marks":[90,55,67,98],
    "City":["delhi", "Jaipur", "Ranpur", "Barilly"]
}




In [50]:
dict1={
    "Name":["Rohan", "seema", "Mahesh", "Shruthi"],
    "Marks":[90,55,67,98],
    "City":["delhi", "Jaipur", "Ranpur", "Barilly"]
}
df=pd.DataFrame(dict1)
print(df)


      Name  Marks     City
0    Rohan     90    delhi
1    seema     55   Jaipur
2   Mahesh     67   Ranpur
3  Shruthi     98  Barilly


In [51]:
df.index=[1,2,3,4]
df


Name  Marks     City
1    Rohan     90    delhi
2    seema     55   Jaipur
3   Mahesh     67   Ranpur
4  Shruthi     98  Barilly

In [52]:
ser=pd.Series(np.random.rand(20))
ser


0     0.294866
1     0.519777
2     0.834503
3     0.904977
4     0.922809
5     0.810076
6     0.226021
7     0.874403
8     0.385538
9     0.537511
10    0.508829
11    0.091312
12    0.562466
13    0.005895
14    0.413199
15    0.198635
16    0.850126
17    0.144259
18    0.307136
19    0.041370
dtype: float64

In [53]:
type(ser)  



pandas.core.series.Series

In [54]:

newdf=pd.DataFrame(np.random.rand(334,5), index=np.arange(334))
newdf


0         1         2         3         4
0    0.112477  0.882037  0.415216  0.021102  0.180312
1    0.841821  0.563796  0.634576  0.793381  0.862956
2    0.313290  0.017151  0.930975  0.287173  0.249914
3    0.737106  0.538709  0.695307  0.004529  0.926442
4    0.430682  0.138821  0.489586  0.469160  0.385037
..        ...       ...       ...       ...       ...
329  0.881716  0.456577  0.761776  0.424125  0.310918
330  0.415050  0.051858  0.673417  0.083290  0.646924
331  0.935935  0.879936  0.772089  0.133673  0.952483
332  0.606305  0.706963  0.194487  0.412627  0.965938
333  0.567331  0.177972  0.969318  0.097232  0.081853

[334 rows x 5 columns]

In [55]:
newdf.head(3)


0         1         2         3         4
0  0.112477  0.882037  0.415216  0.021102  0.180312
1  0.841821  0.563796  0.634576  0.793381  0.862956
2  0.313290  0.017151  0.930975  0.287173  0.249914

In [56]:
newdf.tail(3)


0         1         2         3         4
331  0.935935  0.879936  0.772089  0.133673  0.952483
332  0.606305  0.706963  0.194487  0.412627  0.965938
333  0.567331  0.177972  0.969318  0.097232  0.081853

In [57]:
newdf.sort_index(axis=0)


0         1         2         3         4
0    0.112477  0.882037  0.415216  0.021102  0.180312
1    0.841821  0.563796  0.634576  0.793381  0.862956
2    0.313290  0.017151  0.930975  0.287173  0.249914
3    0.737106  0.538709  0.695307  0.004529  0.926442
4    0.430682  0.138821  0.489586  0.469160  0.385037
..        ...       ...       ...       ...       ...
329  0.881716  0.456577  0.761776  0.424125  0.310918
330  0.415050  0.051858  0.673417  0.083290  0.646924
331  0.935935  0.879936  0.772089  0.133673  0.952483
332  0.606305  0.706963  0.194487  0.412627  0.965938
333  0.567331  0.177972  0.969318  0.097232  0.081853

[334 rows x 5 columns]

In [58]:
newdf.drop(0, axis=1)


1         2         3         4
0    0.882037  0.415216  0.021102  0.180312
1    0.563796  0.634576  0.793381  0.862956
2    0.017151  0.930975  0.287173  0.249914
3    0.538709  0.695307  0.004529  0.926442
4    0.138821  0.489586  0.469160  0.385037
..        ...       ...       ...       ...
329  0.456577  0.761776  0.424125  0.310918
330  0.051858  0.673417  0.083290  0.646924
331  0.879936  0.772089  0.133673  0.952483
332  0.706963  0.194487  0.412627  0.965938
333  0.177972  0.969318  0.097232  0.081853

[334 rows x 4 columns]

In [59]:
newdf.dropna(inplace=True)